import type { NodeConfig, WireConfig } from "./types";

export const NODES: NodeConfig[] = [
  // Main modules
  { id: "pc", x: 300, y: 510, w: 250, h: 40, label: "PC", type: "main" }, 
  { id: "nextPC", x: 300, y: 570, w: 250, h: 40, label: "Next PC", type: "sub" }, 
  { id: "incPC", x: 100, y: 445, w: 100, h: 40, label: "Increment PC", type: "sub" }, 
  { id: "regfile", x: 300, y: 250, w: 250, h: 80, label: "Register File", type: "main" },
  { id: "regfile_E", x: 520, y: 250, w: 30, h: 30, label: "E", type: "main" },
  { id: "regfile_M", x: 520, y: 300, w: 30, h: 30, label: "M", type: "main" },
  { id: "alu", x: 550, y: 50, w: 200, h: 60, label: "ALU", type: "main" },
  { id: "cc", x: 400, y: 60, w: 50, h: 40, label: "CC", type: "main" },
  { id: "mem", x: 900, y: 50, w: 100, h: 500, label: "Memory", type: "main" },
  { id: "data", x: 820, y: 275, w: 50, h: 50, label: "Data", type: "sub" }, 
  { id: "addr", x: 820, y: 180, w: 50, h: 50, label: "Addr", type: "sub" }, 
  { id: "memCtrl", x: 820, y: 400, w: 50, h: 50, label: "MemC", type: "sub" }, 
  { id: "aluA", x: 575, y: 125, w: 50, h: 20, label: "ALU A", type: "sub" },
  { id: "aluB", x: 675, y: 125, w: 50, h: 20, label: "ALU B", type: "sub" },
  { id: "dstE", x: 500, y: 220, w: 50, h: 20, label: "dstE", type: "sub" },
  { id: "dstM", x: 510, y: 360, w: 50, h: 20, label: "dstM", type: "sub" },
  { id: "srcA", x: 390, y: 360, w: 50, h: 20, label: "srcA", type: "sub" },
  { id: "srcB", x: 450, y: 360, w: 50, h: 20, label: "srcB", type: "sub" },
  { id: "setcc", x: 400, y: 105, w: 50, h: 20, label: "setcc", type: "sub" },

  // Signals
  { id: "icode", x: 300, y: 450, w: 50, h: 30, label: "icode", type: "signal" },
  { id: "ifun", x: 350, y: 450, w: 50, h: 30, label: "ifun", type: "signal" }, 
  { id: "rA", x: 400, y: 450, w: 50, h: 30, label: "rA", type: "signal" }, 
  { id: "rB", x: 450, y: 450, w: 50, h: 30, label: "rB", type: "signal" }, 
  { id: "valC", x: 500, y: 450, w: 50, h: 30, label: "valC", type: "signal" }, 
  { id: "valA", x: 375, y: 180, w: 50, h: 30, label: "valA", type: "signal" },
  { id: "valB", x: 425, y: 180, w: 50, h: 30, label: "valB", type: "signal" },
  { id: "valE", x: 770, y: 65, w: 50, h: 30, label: "valE", type: "signal" },
  { id: "valM", x: 770, y: 355, w: 50, h: 30, label: "valM", type: "signal" },
  { id: "cond", x: 180, y: 65, w: 60, h: 30, label: "cond", type: "signal" },
  { id: "valP", x: 125, y: 400, w: 50, h: 30, label: "valP", type: "signal" }, 

  // Junctions
  { id: "j_mem_icode", x: 325, y: 495, w: 1, h: 1, label: '', type: "junction" }, 
  { id: "j_mem_ifun", x: 375, y: 495, w: 1, h: 1, label: '', type: "junction" }, 
  { id: "j_mem_rA", x: 425, y: 495, w: 1, h: 1, label: '', type: "junction" }, 
  { id: "j_mem_rB", x: 475, y: 495, w: 1, h: 1, label: '', type: "junction" }, 
  { id: "j_mem_valC", x: 525, y: 495, w: 1, h: 1, label: '', type: "junction" }, 
  { id: "j_icode_incPC", x: 250, y: 465, w: 1, h: 1, label: '', type: "junction" }, 
  { id: "j_ifun", x: 375, y: 425, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_valA", x: 560, y: 135, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_valB", x: 700, y: 195, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode", x: 325, y: 410, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_srcA", x: 405, y: 410, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_srcB", x: 460, y: 410, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_dstM", x: 535, y: 410, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_aluA", x: 580, y: 410, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_dstE", x: 580, y: 210, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_memCtrl", x: 680, y: 410, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_data", x: 680, y: 285, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_icode_addr", x: 680, y: 215, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_rA", x: 425, y: 395, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_rB", x: 475, y: 440, w: 1, h: 1, label: '', type: "junction" },
  { id: "j_valC", x: 600, y: 465, w: 1, h: 1, label: '', type: "junction" },
];

export const WIRES: WireConfig[] = [
  { id: "valC->j_valC", from: "valC", to: "j_valC" },
  { id: "j_valC->aluA", from: "j_valC", to: "aluA", arrow: "end", },
  { id: "j_valC->nextPC", from: "j_valC", to: "nextPC", arrow: "end", waypoints: [{x: 600, y: 575}], toAnchor: {side: "right", offset: 5 } },
  { id: "rA->j_rA", from: "rA", to: "j_rA" },
  { id: "j_rA->srcA", from: "j_rA", to: "srcA", arrow: "end", toAnchor: { side: "bottom", offset: 35 } },
  { id: "j_rA->dstM", from: "j_rA", to: "dstM", arrow: "end", waypoints: [{x: 520, y: 395}],  toAnchor: { side: "bottom", offset: 10 } },
  { id: "rB->j_rB", from: "rB", to: "j_rB" },
  { id: "j_rB->srcB", from: "j_rB", to: "srcB", arrow: "end" },
  { id: "j_rB->dstE", from: "j_rB", to: "dstE", arrow: "end", waypoints: [{x: 570, y: 440}, {x: 570, y: 230}], toAnchor: { side: "right" } },
  { id: "icode->j_icode", from: "icode", to: "j_icode" },
  { id: "j_icode->j_icode_srcA", from: "j_icode", to: "j_icode_srcA" },
  { id: "j_icode_srcA->srcA", from: "j_icode_srcA", to: "srcA", arrow: "end", toAnchor: { side: "bottom", offset: 15 } },
  { id: "j_icode_srcA->j_icode_srcB", from: "j_icode_srcA", to: "j_icode_srcB" },
  { id: "j_icode_srcB->srcB", from: "j_icode_srcB", to: "srcB", arrow: "end", toAnchor: { side: "bottom", offset: 10 } },
  { id: "j_icode_srcB->j_icode_dstM", from: "j_icode_srcB", to: "j_icode_dstM" },
  { id: "j_icode_dstM->dstM", from: "j_icode_dstM", to: "dstM", arrow: "end" },
  { id: "j_icode_dstM->j_icode_aluA", from: "j_icode_dstM", to: "j_icode_aluA" },
  { id: "j_icode_aluA->j_icode_dstE", from: "j_icode_aluA", to: "j_icode_dstE" },
  { id: "j_icode_dstE->aluA", from: "j_icode_dstE", to: "aluA", arrow: "end", toAnchor: { side: "bottom", offset: 5 } },
  { id: "j_icode_dstE->dstE", from: "j_icode_dstE", to: "dstE", arrow: "end", waypoints: [{x: 525, y: 210 }] },
  { id: "j_icode_aluA->j_icode_memCtrl", from: "j_icode_aluA", to: "j_icode_memCtrl" },
  { id: "j_icode_memCtrl->memCtrl", from: "j_icode_memCtrl", to: "memCtrl", arrow: "end", toAnchor: { side: "left", offset: 10 } },
  { id: "j_icode_memCtrl->j_icode_data", from: "j_icode_memCtrl", to: "j_icode_data" },
  { id: "j_icode_data->data", from: "j_icode_data", to: "data", arrow: "end", toAnchor: { side: "left", offset: 10 } },
  { id: "j_icode_data->j_icode_addr", from: "j_icode_data", to: "j_icode_addr" },
  { id: "j_icode_addr->aluB", from: "j_icode_addr", to: "aluB", arrow: "end", toAnchor: { side: "bottom", offset: 5 } },
  { id: "j_icode_addr->addr", from: "j_icode_addr", to: "addr", arrow: "end", toAnchor: { side: "left", offset: 35 } },
  { id: "nextPC->pc", from: "nextPC", to: "pc", arrow: "end" },
  { id: "pc->incPC", from: "pc", to: "incPC", arrow: "end", waypoints: [{ x: 150, y: 530 }] },
  { id: "incPC->valP", from: "incPC", to: "valP", arrow: "end" },
  { id: "valP->nextPC", from: "valP", to: "nextPC", arrow: "end", waypoints: [{ x: 80, y: 415 }, { x: 80, y: 590 }] },
  { id: "valP->data", from: "valP", to: "data", arrow: "end", waypoints: [{ x: 150, y: 345 }, { x: 845, y: 345 }] },
  { id: "pc->mem", from: "pc", to: "mem", arrow: "end", toAnchor: { side: "left", offset: 480 } },
  { id: "data->mem", from: "data", to: "mem", arrow: "end" },
  { id: "addr->mem", from: "addr", to: "mem", arrow: "end", toAnchor: { side: "left", offset: 155 } },
  { id: "memCtrl->mem", from: "memCtrl", to: "mem", arrow: "end", toAnchor: { side: "left", offset: 375 } },
  { id: "mem->j_mem_valC", from: "mem", to: "j_mem_valC", fromAnchor: { side: "left", offset: 445 } },
  { id: "alu->cc", from: "alu", to: "cc", arrow: "end" },
  { id: "cc->cond", from: "cc", to: "cond", arrow: "end" },
  { id: "cond->nextPC", from: "cond", to: "nextPC", arrow: "end", waypoints: [{ x: 40, y: 80 }, { x: 40, y: 605 }], toAnchor: { side: "left", offset: 35 } },
  { id: "cond->dstE", from: "cond", to: "dstE", arrow: "end", waypoints: [{ x: 210, y: 35 }, { x: 505, y: 35 }], toAnchor: { side: "top", offset: 5 } },
  { id: "j_mem_valC->j_mem_rB", from: "j_mem_valC", to: "j_mem_rB" },
  { id: "j_mem_rB->j_mem_rA", from: "j_mem_rB", to: "j_mem_rA" },
  { id: "j_mem_rA->j_mem_ifun", from: "j_mem_rA", to: "j_mem_ifun" },
  { id: "j_mem_ifun->j_mem_icode", from: "j_mem_ifun", to: "j_mem_icode" },
  { id: "j_mem_icode->icode", from: "j_mem_icode", to: "icode", arrow: "end" },
  { id: "j_mem_ifun->ifun", from: "j_mem_ifun", to: "ifun", arrow: "end" },
  { id: "ifun->j_ifun", from: "ifun", to: "j_ifun" },
  { id: "j_ifun->cond", from: "j_ifun", to: "cond", arrow: "end", waypoints: [{ x: 375, y: 370 }, { x: 210, y: 370 }] },
  { id: "j_ifun->alu", from: "j_ifun", to: "alu", arrow: "end", waypoints: [{ x: 650, y: 425 }] },
  { id: "j_mem_rA->rA", from: "j_mem_rA", to: "rA", arrow: "end" },
  { id: "j_mem_rB->rB", from: "j_mem_rB", to: "rB", arrow: "end" },
  { id: "j_mem_valC->valC", from: "j_mem_valC", to: "valC", arrow: "end" },
  { id: "icode->j_icode_incPC", from: "icode", to: "j_icode_incPC" },
  { id: "j_icode->setcc", from: "j_icode", to: "setcc", waypoints: [{ x: 250, y: 410 }, {x: 250, y: 115 }], arrow: "end", toAnchor: {side: "left"} },
  { id: "j_icode_incPC->incPC", from: "j_icode_incPC", to: "incPC", arrow: "end" },
  { id: "j_icode_incPC->nextPC", from: "j_icode_incPC", to: "nextPC", arrow: "end", waypoints: [{ x: 250, y: 575 }], toAnchor: { side: "left", offset: 5 } },
  { id: "mem->valM", from: "mem", to: "valM", arrow: "end", fromAnchor: { side: "left", offset: 320 } },
  { id: "valM->nextPC", from: "valM", to: "nextPC", arrow: "end", waypoints: [{ x: 795, y: 590 }] },
  { id: "valM->regfile_M", from: "valM", to: "regfile_M", arrow: "end", waypoints: [{ x: 795, y: 315 }] },
  { id: "alu->valE", from: "alu", to: "valE", arrow: "end" },
  { id: "aluA->alu", from: "aluA", to: "alu", arrow: "end", toAnchor: { side: "bottom", offset: 50 } },
  { id: "aluB->alu", from: "aluB", to: "alu", arrow: "end", toAnchor: { side: "bottom", offset: 150 } },
  { id: "valE->regfile_E", from: "valE", to: "regfile_E", arrow: "end", waypoints: [{ x: 795, y: 265 }] },
  { id: "dstE->regfile_E", from: "dstE", to: "regfile_E", arrow: "end", fromAnchor: { side: "bottom", offset: 35 } },
  { id: "dstM->regfile_M", from: "dstM", to: "regfile_M", arrow: "end" },
  { id: "srcA->regfile", from: "srcA", to: "regfile", arrow: "end", toAnchor: { side: "bottom", offset: 115 } },
  { id: "srcB->regfile", from: "srcB", to: "regfile", arrow: "end", toAnchor: { side: "bottom", offset: 175 } },
  { id: "valE->addr", from: "valE", to: "addr", arrow: "end", waypoints: [{ x: 845, y: 80 }] },
  { id: "regfile->valA", from: "regfile", to: "valA", arrow: "end", fromAnchor: { side: "top", offset: 100 } },
  { id: "regfile->valB", from: "regfile", to: "valB", arrow: "end", fromAnchor: { side: "top", offset: 150 } },
  { id: "valB->j_valB", from: "valB", to: "j_valB" },
  { id: "j_valB->addr", from: "j_valB", to: "addr", arrow: "end", toAnchor: { side: "left", offset: 15 } },
  { id: "j_valB->aluB", from: "j_valB", to: "aluB", arrow: "end" },
  { id: "valA->j_valA", from: "valA", to: "j_valA", waypoints: [{ x: 400, y: 135 }] },
  { id: "j_valA->aluA", from: "j_valA", to: "aluA", arrow: "end" },
  { id: "j_valA->data", from: "j_valA", to: "data", arrow: "end", waypoints: [{ x: 560, y: 300 }] },
];